//! Tests for the dependency vulnerability detector (spec §18.5).

use arbitraitor_analysis::dep_vuln::{Advisory, DepVulnDetector, LockfileFormat};
use arbitraitor_model::ids::Sha256Digest;
use arbitraitor_model::verdict::Severity;

fn test_digest() -> Sha256Digest {
    Sha256Digest::new([0xab; 32])
}

fn cargo_lock() -> &'static [u8] {
    b"\
# This file is automatically @generated by Cargo.
[[package]]
name = \"serde\"
version = \"1.0.0\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"

[[package]]
name = \"rand\"
version = \"0.8.5\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"
"
}

fn npm_lock() -> &'static [u8] {
    b"{\
\"lockfileVersion\": 3,\
\"packages\": {\
  \"\": {\"version\": \"1.0.0\"},\
  \"node_modules/express\": {\"version\": \"4.18.0\"},\
  \"node_modules/lodash\": {\"version\": \"4.17.20\"}\
}\
}"
}

fn advisory(
    id: &str,
    ecosystem: &str,
    package: &str,
    range: &str,
    severity: &str,
    is_kev: bool,
) -> Advisory {
    Advisory {
        id: id.to_owned(),
        ecosystem: ecosystem.to_owned(),
        package: package.to_owned(),
        affected_range: range.to_owned(),
        severity: severity.to_owned(),
        is_kev,
    }
}

mod detect_format {
    use super::*;

    #[test]
    fn cargo() {
        assert_eq!(
            DepVulnDetector::detect_format(cargo_lock()),
            Some(LockfileFormat::CargoLock)
        );
    }

    #[test]
    fn npm() {
        assert_eq!(
            DepVulnDetector::detect_format(npm_lock()),
            Some(LockfileFormat::NpmLock)
        );
    }

    #[test]
    fn non_lockfile_returns_none() {
        assert_eq!(DepVulnDetector::detect_format(b"hello world"), None);
        assert_eq!(
            DepVulnDetector::detect_format(b"#!/bin/bash\necho hi"),
            None
        );
    }
}

mod parse_packages {
    use super::*;

    #[test]
    fn cargo_lock_extracts() {
        let packages = DepVulnDetector::parse_packages(cargo_lock(), LockfileFormat::CargoLock);
        assert_eq!(packages.len(), 2);
        assert!(
            packages
                .iter()
                .any(|p| p.name == "serde" && p.version == "1.0.0")
        );
        assert!(
            packages
                .iter()
                .any(|p| p.name == "rand" && p.version == "0.8.5")
        );
    }

    #[test]
    fn npm_lock_extracts() {
        let packages = DepVulnDetector::parse_packages(npm_lock(), LockfileFormat::NpmLock);
        assert!(
            packages
                .iter()
                .any(|p| p.name == "express" && p.version == "4.18.0")
        );
        assert!(
            packages
                .iter()
                .any(|p| p.name == "lodash" && p.version == "4.17.20")
        );
    }
}

mod version_matching {
    use super::*;

    #[test]
    fn wildcard() {
        assert!(DepVulnDetector::version_matches("1.0.0", "*"));
    }

    #[test]
    fn exact() {
        assert!(DepVulnDetector::version_matches("1.0.0", "==1.0.0"));
        assert!(!DepVulnDetector::version_matches("1.0.1", "==1.0.0"));
    }

    #[test]
    fn gte() {
        assert!(DepVulnDetector::version_matches("2.0.0", ">=1.0.0"));
        assert!(!DepVulnDetector::version_matches("0.9.0", ">=1.0.0"));
    }
}

mod end_to_end {
    use super::*;
    use arbitraitor_analysis::{AnalysisContext, Detector};
    use arbitraitor_artifact::classify;
    use sha2::{Digest, Sha256};

    fn ctx(bytes: &[u8]) -> AnalysisContext<'_> {
        AnalysisContext {
            artifact_bytes: bytes,
            classification: classify(bytes),
            retrieval: None,
            artifact_sha256: Sha256Digest::new(Sha256::digest(bytes).into()),
        }
    }

    #[test]
    fn empty_snapshot_no_findings() {
        let detector = DepVulnDetector::empty(test_digest());
        assert!(detector.analyze(&ctx(cargo_lock())).is_empty());
    }

    #[test]
    fn matched_advisory_produces_finding() {
        let detector = DepVulnDetector::new(
            vec![advisory(
                "GHSA-TEST-1",
                "crates.io",
                "serde",
                ">=1.0.0",
                "high",
                false,
            )],
            test_digest(),
        );
        let findings = detector.analyze(&ctx(cargo_lock()));
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].severity, Severity::High);
        assert!(findings[0].id.contains("serde"));
        assert!(!findings[0].taxonomies.is_empty());
    }

    #[test]
    fn kev_advisory_produces_confirmed_finding() {
        use arbitraitor_model::verdict::Confidence;

        let detector = DepVulnDetector::new(
            vec![advisory(
                "CVE-2026-KEV",
                "crates.io",
                "serde",
                "*",
                "critical",
                true,
            )],
            test_digest(),
        );
        let findings = detector.analyze(&ctx(cargo_lock()));
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].confidence, Confidence::Confirmed);
        assert!(findings[0].description.contains("KEV"));
    }

    #[test]
    fn non_matching_advisory_produces_no_finding() {
        let detector = DepVulnDetector::new(
            vec![advisory(
                "GHSA-NOMATCH",
                "crates.io",
                "nonexistent",
                "*",
                "high",
                false,
            )],
            test_digest(),
        );
        assert!(detector.analyze(&ctx(cargo_lock())).is_empty());
    }

    #[test]
    fn npm_lock_with_npm_advisory() {
        let detector = DepVulnDetector::new(
            vec![advisory(
                "GHSA-NPM-1",
                "npm",
                "lodash",
                "==4.17.20",
                "high",
                false,
            )],
            test_digest(),
        );
        let findings = detector.analyze(&ctx(npm_lock()));
        assert_eq!(findings.len(), 1);
        assert!(findings[0].id.contains("lodash"));
    }
}
